theme: jekyll-theme-minimal
title: Why Privacy Matters
description: The ability to maintain privacy from governments, corporations, and our peers is fundamental to a free, democratic, and equitable society. \n\n This website is a collaborative project maintained by [Miles McCain](https://rmrm.io). View the contributors [here](CONTRIBUTORS.md).
