# Site settings
title: Why Privacy Matters
logo: assets/icon.png
description: Privacy is important. Here are some simple reasons why.
url: https://whyprivacymatters.org
lang: en


# Gems
gems:
- jekyll-seo-tag

# Build Settings
permalink: :title/
sass:
  sass_dir: css

# Paths
defaults:
  -
    scope:
      path: "README.md"
    values:
      permalink: "/"
